name: "IP_CF Min"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  hin-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php index.php
          git config --global user.email "Rango_CFS@gmail.com"
          git config --global user.name "Rango_CFS"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push